import * as vscode from "vscode";

const HELPER_FILE_NAME = "_exconvex.ts";

const HELPER_CONTENT = `/* eslint-disable */
// Auto-generated by ExConvex extension — DO NOT EDIT
// This file provides data browsing queries for the ExConvex VS Code extension.
// Safe to delete if you uninstall the extension.

import { query } from "./_generated/server";
import { v } from "convex/values";

export const _listDocs = query({
  args: { table: v.string(), limit: v.optional(v.number()) },
  handler: async (ctx, { table, limit }) => {
    const take = limit ?? 50;
    return await (ctx.db as any).query(table).take(take);
  },
});

export const _countDocs = query({
  args: { table: v.string() },
  handler: async (ctx, { table }) => {
    const docs = await (ctx.db as any).query(table).collect();
    return { table, count: docs.length };
  },
});

export const _getDoc = query({
  args: { table: v.string(), id: v.string() },
  handler: async (ctx, { table, id }) => {
    return await (ctx.db as any).get(id);
  },
});

export const _tableCounts = query({
  args: { tables: v.array(v.string()) },
  handler: async (ctx, { tables }) => {
    const counts: Record<string, number> = {};
    for (const table of tables) {
      const docs = await (ctx.db as any).query(table).collect();
      counts[table] = docs.length;
    }
    return counts;
  },
});
`;

/**
 * Find the convex directory and ensure the helper file exists.
 * Returns the convex directory URI or null.
 */
export async function ensureHelperFile(): Promise<vscode.Uri | null> {
  const convexDir = await findConvexDir();
  if (!convexDir) {
    vscode.window.showWarningMessage(
      "Could not find a convex/ directory in this workspace."
    );
    return null;
  }

  const helperUri = vscode.Uri.joinPath(convexDir, HELPER_FILE_NAME);

  try {
    await vscode.workspace.fs.stat(helperUri);
    // File exists — check if it needs updating
    const existing = Buffer.from(
      await vscode.workspace.fs.readFile(helperUri)
    ).toString("utf-8");
    if (!existing.includes("_listDocs") || !existing.includes("_tableCounts")) {
      await writeHelper(helperUri);
    }
  } catch {
    // File doesn't exist — create it
    const action = await vscode.window.showInformationMessage(
      "ExConvex needs to create a helper file in your convex/ directory to browse live data. This file is safe to delete later.",
      "Create",
      "Cancel"
    );
    if (action !== "Create") {
      return null;
    }
    await writeHelper(helperUri);
    vscode.window.showInformationMessage(
      `Created ${HELPER_FILE_NAME} in your convex directory. Run "npx convex dev" to deploy it.`
    );
  }

  return convexDir;
}

async function writeHelper(uri: vscode.Uri): Promise<void> {
  await vscode.workspace.fs.writeFile(
    uri,
    Buffer.from(HELPER_CONTENT, "utf-8")
  );
}

/**
 * Remove the helper file from the convex directory.
 */
export async function removeHelperFile(): Promise<void> {
  const convexDir = await findConvexDir();
  if (!convexDir) {return;}

  const helperUri = vscode.Uri.joinPath(convexDir, HELPER_FILE_NAME);
  try {
    await vscode.workspace.fs.delete(helperUri);
  } catch {
    // File doesn't exist
  }
}

async function findConvexDir(): Promise<vscode.Uri | null> {
  const workspaceFolders = vscode.workspace.workspaceFolders;
  if (!workspaceFolders?.length) {return null;}

  const pattern = new vscode.RelativePattern(
    workspaceFolders[0],
    "**/convex/_generated/server.{js,ts,d.ts}"
  );
  const files = await vscode.workspace.findFiles(
    pattern,
    "**/node_modules/**",
    5
  );

  if (files.length === 0) {return null;}

  // The convex dir is two levels up from _generated/server.ts
  files.sort((a, b) => a.fsPath.length - b.fsPath.length);
  return vscode.Uri.joinPath(files[0], "..", "..");
}
