import * as vscode from "vscode";
import { findConvexDir as findConvexDirShared } from "../convexProject";

const HELPER_DIR_NAME = ".exconvex";
const HELPER_FILE_NAME = "_exconvex.ts";

const HELPER_CONTENT = `/* eslint-disable */
// Auto-generated by ExConvex extension — DO NOT EDIT
// This file provides data browsing queries for the ExConvex VS Code extension.
// Safe to delete if you uninstall the extension.

import { query } from "./_generated/server";
import { v } from "convex/values";

export const _listDocs = query({
  args: { table: v.string(), limit: v.optional(v.number()) },
  handler: async (ctx, { table, limit }) => {
    const take = limit ?? 50;
    return await (ctx.db as any).query(table).take(take);
  },
});

export const _countDocs = query({
  args: { table: v.string() },
  handler: async (ctx, { table }) => {
    // Only count up to 10,000 documents to avoid memory exhaustion
    const docs = await (ctx.db as any).query(table).take(10000);
    return { table, count: docs.length, hasMore: docs.length === 10000 };
  },
});

export const _getDoc = query({
  args: { table: v.string(), id: v.string() },
  handler: async (ctx, { table, id }) => {
    return await (ctx.db as any).get(id);
  },
});

export const _tableCounts = query({
  args: { tables: v.array(v.string()) },
  handler: async (ctx, { tables }) => {
    const counts: Record<string, number> = {};
    for (const table of tables) {
      // Only count up to 10,000 documents to avoid memory exhaustion
      const docs = await (ctx.db as any).query(table).take(10000);
      counts[table] = docs.length;
    }
    return counts;
  },
});

import { mutation } from "./_generated/server";

export const _updateDoc = mutation({
  args: { 
    table: v.string(),
    id: v.string(), 
    field: v.string(), 
    value: v.any() 
  },
  handler: async (ctx, { table, id, field, value }) => {
    const normalizedId = (ctx.db as any).normalizeId(table, id);
    if (!normalizedId) {
      throw new Error(\`Invalid ID "\${id}" for table "\${table}"\`);
    }
    await (ctx.db as any).patch(normalizedId, { [field]: value });
    return { success: true };
  },
});

export const _createDoc = mutation({
  args: {
    table: v.string(),
    document: v.any()
  },
  handler: async (ctx, { table, document }) => {
    const id = await (ctx.db as any).insert(table, document);
    return { id };
  }
});
`;

/**
 * Find the convex directory and ensure the helper file exists.
 * Returns the convex directory URI or null.
 */
export async function ensureHelperFile(): Promise<vscode.Uri | null> {
  const convexDir = await findConvexDirShared();
  if (!convexDir) {
    vscode.window.showWarningMessage(
      "Could not find a convex/ directory in this workspace."
    );
    return null;
  }

  const helperDirUri = vscode.Uri.joinPath(convexDir, HELPER_DIR_NAME);
  const helperUri = vscode.Uri.joinPath(helperDirUri, HELPER_FILE_NAME);

  try {
    await vscode.workspace.fs.stat(helperUri);
    // File exists — check if it needs updating
    const existing = Buffer.from(
      await vscode.workspace.fs.readFile(helperUri)
    ).toString("utf-8");
    if (!existing.includes("_listDocs") || !existing.includes("_tableCounts") || !existing.includes("normalizeId") || !existing.includes("_createDoc")) {
      await writeHelper(helperDirUri, helperUri);
    }
  } catch {
    // File doesn't exist — create it
    const action = await vscode.window.showInformationMessage(
      "ExConvex needs to create a helper file in your convex/ directory to browse live data. This will be placed in a hidden, gitignored folder (.exconvex).",
      "Create",
      "Cancel"
    );
    if (action !== "Create") {
      return null;
    }
    await writeHelper(helperDirUri, helperUri);
    vscode.window.showInformationMessage(
      `Created ${HELPER_DIR_NAME}/${HELPER_FILE_NAME} in your convex directory. Run "npx convex dev" to deploy it.`
    );
  }

  return convexDir;
}

async function writeHelper(dirUri: vscode.Uri, fileUri: vscode.Uri): Promise<void> {
  // Ensure the .exconvex directory exists
  await vscode.workspace.fs.createDirectory(dirUri);

  // Write the local .gitignore to exclude this folder from the user's repo
  const gitignoreUri = vscode.Uri.joinPath(dirUri, ".gitignore");
  await vscode.workspace.fs.writeFile(
    gitignoreUri,
    Buffer.from("*\n", "utf-8")
  );

  // Write the actual helper file
  await vscode.workspace.fs.writeFile(
    fileUri,
    Buffer.from(HELPER_CONTENT, "utf-8")
  );
}

/**
 * Remove the helper directory from the convex directory.
 */
export async function removeHelperFile(): Promise<void> {
  const convexDir = await findConvexDirShared();
  if (!convexDir) { return; }

  const helperDirUri = vscode.Uri.joinPath(convexDir, HELPER_DIR_NAME);
  try {
    await vscode.workspace.fs.delete(helperDirUri, { recursive: true, useTrash: false });
  } catch {
    // Directory doesn't exist
  }
}

